### ISSUE TITLE
panic occurred when open cpu `generate` on testnet

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qng#283]
```bash
2022-11-12|00:04:24.525 [INFO ] System info                         QNG Version=1.0.17+dev-e5598dd Go version=go1.18.5
2022-11-12|00:04:24.525 [INFO ] System info                         Home dir="/Users/blocklee/Library/Application Support/Qng"
2022-11-12|00:04:24.525 [INFO ] Loading block database              dbPath=data/testnet/blocks_ffldb
2022-11-12|00:04:24.615 [INFO ] Block database loaded 
2022-11-12|00:04:24.744 [INFO ] Start Peers from:data/testnet/peerstore module=P2P
2022-11-12|00:04:24.744 [DEBUG] ECDSA private key generated         module=P2P
2022-11-12|00:04:24.810 [INFO ] Transaction index is enabled        module=node
2022-11-12|00:04:24.810 [DEBUG] k=0 sum=0.8646647167633873 
2022-11-12|00:04:24.810 [DEBUG] k=1 sum=0.5939941502901619 
2022-11-12|00:04:24.810 [DEBUG] k=2 sum=0.3233235838169365 
2022-11-12|00:04:24.810 [DEBUG] k=3 sum=0.1428765395014529 
2022-11-12|00:04:24.810 [DEBUG] k=4 sum=0.05265301734371111 
2022-11-12|00:04:24.810 [DEBUG] k=5 sum=0.01656360848061439 
2022-11-12|00:04:24.810 [DEBUG] k=6 sum=0.004533805526248817 
2022-11-12|00:04:24.810 [INFO ] anticone size:6                     module=blockdag
2022-11-12|00:04:24.812 [INFO ] Loading dag ...                     module=blockchain
2022-11-12|00:04:50.463 [INFO ] Dag loaded:loadTime=25.631754586s   module=blockchain
2022-11-12|00:04:50.484 [DEBUG] Current internal block              block order=460461
2022-11-12|00:04:50.484 [DEBUG] Current transaction index tip       order=460461 hash=afa48b55e7a2dfedfa329acd22b4ee29b138d95be45eac03059d20f0cec1ca29
2022-11-12|00:04:58.208 [INFO ] DAG Type:phantom                    module=blockchain
2022-11-12|00:04:58.209 [INFO ] Blockchain database version         module=blockchain chain=11 compression=1 index=1
2022-11-12|00:04:58.209 [INFO ] Chain state:totaltx=464869 tipsNum=16 mainOrder=460461 total=462673 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=1b71cc419ed4f70dba4dd28374020e59ca20fa7a7354bd58610d92b3cbb70957,order=uncertainty,height=460118 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=afa48b55e7a2dfedfa329acd22b4ee29b138d95be45eac03059d20f0cec1ca29,order=460461,height=460210 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=760d7ebc03c0faae8ce280e285049e1d3cd1284411cec8e9324147c6d1894e17,order=uncertainty,height=459987 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=222d5e7f14db9925d7f0b036f5988205564503f270560982c8ab1dd5537f48d2,order=uncertainty,height=460085 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=fb18d18a64d2f48f389f4b02305e20af66ef0bb73e9044f38e24cfed4fe5c947,order=uncertainty,height=459853 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=230221ea8f5d40e250814c9434071ddd4693d80c65cf55b2eaa0b1f92c8f74b7,order=uncertainty,height=460135 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=b9abb22a3f40fe9be579baca67266103856f3d9d9c0fd8fca4a2f1f72a4fffab,order=uncertainty,height=459904 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=19efdd96379e8ace4daf1b45871a4751703841ca7ff1ae9f1a50624a3d8ba870,order=uncertainty,height=459897 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=206522f924b06b4ee2989fd2dcbf96085fc651dbd499ca120ea6de029b08e587,order=uncertainty,height=459526 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=d1e74156b5cbc110a8278c153fd30d1a26e83ba008253391af46f6ca6893a64f,order=uncertainty,height=460078 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=270be000cd5eec6b085253c23a6e46e0b405141ed0362a37a8c5d5282755ace9,order=uncertainty,height=459585 module=blockchain
2022-11-12|00:04:58.209 [INFO ] hash=29b377014a8533fa871f7fb3050c6344e80d4be8bea43d57701c9835f2d41756,order=uncertainty,height=459612 module=blockchain
2022-11-12|00:04:58.210 [INFO ] hash=5eb92b78c3b263deb7e232f6d02b275d6872118da33237fb4e1542318418bdd7,order=uncertainty,height=459927 module=blockchain
2022-11-12|00:04:58.210 [INFO ] hash=b72e3da7bddc6fead1bd517f635b82effdd78eb07c58f53096abeb4c5ee8f87d,order=uncertainty,height=460001 module=blockchain
2022-11-12|00:04:58.210 [INFO ] hash=d8197515028f422f79454f953d5744239a6a79ffc34a07ceaf9f664ad7de1766,order=uncertainty,height=460005 module=blockchain
2022-11-12|00:04:58.210 [INFO ] hash=4548629d7e049f07895f1088a54d8f0efbb87d980767e02eeefe53d4dc9ace55,order=uncertainty,height=460020 module=blockchain
2022-11-12|00:04:58.210 [INFO ] ZMQ:Not Supported                   module=zmq
2022-11-12|00:04:58.210 [DEBUG] Register vm meerevm                 module=vm
2022-11-12|00:04:58.210 [DEBUG] RPC Service API registered. NameSpace:qitmeer     *p2p.PublicP2PAPI module=node
2022-11-12|00:04:58.210 [DEBUG] RPC Service API registered. NameSpace:qitmeer     *blkmgr.PublicBlockAPI module=node
2022-11-12|00:04:58.210 [DEBUG] RPC Service API registered. NameSpace:qitmeer     *tx.PublicTxAPI module=node
2022-11-12|00:04:58.211 [DEBUG] RPC Service API registered. NameSpace:qitmeer     *mempool.PublicMempoolAPI module=node
2022-11-12|00:04:58.211 [DEBUG] RPC Service API registered. NameSpace:qitmeer     *miner.PublicMinerAPI module=node
2022-11-12|00:04:58.211 [DEBUG] RPC Service API registered. NameSpace:qitmeer     *vm.PublicVMAPI module=node
2022-11-12|00:04:58.211 [DEBUG] RPC Service API registered. NameSpace:qitmeer     *acct.PublicAccountManagerAPI module=node
2022-11-12|00:04:58.211 [DEBUG] RPC Service API registered. NameSpace:qitmeer     *address.PublicAddressAPI module=node
2022-11-12|00:04:58.211 [DEBUG] RPC Service API registered. NameSpace:qitmeer     *node.PublicBlockChainAPI module=node
2022-11-12|00:04:58.211 [INFO ] Starting Node                       module=node
2022-11-12|00:04:58.211 [DEBUG] Starting 1 services: [*node.QitmeerFull] module=service
2022-11-12|00:04:58.211 [DEBUG] Starting service type *node.QitmeerFull module=service
2022-11-12|00:04:58.211 [DEBUG] (*node.QitmeerFull) service start   module=service
2022-11-12|00:04:58.211 [DEBUG] Starting 8 services: [*notifymgr.NotifyMgr *blkmgr.BlockManager *miner.Miner *vm.Service *acct.AccountManager *rpc.RpcServer *tx.TxManager *p2p.Service] module=service
2022-11-12|00:04:58.211 [DEBUG] Starting service type *notifymgr.NotifyMgr module=service
2022-11-12|00:04:58.211 [DEBUG] (*notifymgr.NotifyMgr) service start module=service
2022-11-12|00:04:58.211 [INFO ] Start NotifyMgr... 
2022-11-12|00:04:58.211 [DEBUG] Starting service type *blkmgr.BlockManager module=service
2022-11-12|00:04:58.211 [DEBUG] (*blkmgr.BlockManager) service start module=service
2022-11-12|00:04:58.211 [DEBUG] Starting service type *miner.Miner  module=service
2022-11-12|00:04:58.211 [DEBUG] (*miner.Miner) service start        module=service
2022-11-12|00:04:58.211 [INFO ] Start Miner...                      module=miner
2022-11-12|00:04:58.212 [DEBUG] Starting service type *vm.Service   module=service
2022-11-12|00:04:58.212 [INFO ] Starting Virtual Machines Service   module=vm
2022-11-12|00:04:58.212 [DEBUG] (*vm.Service) service start         module=service
2022-11-12|00:04:58.212 [INFO ] System info                         module=EVM        ETH VM Version=meervm-v0.0.2 Go version=go1.18.5
2022-11-12|00:04:58.212 [INFO ] Init Coinbase PK Address:Tk6tw7BzzeWHzo79eeBtWRtr6Y8S3VLK3aLHFwfTTMAY656Y8F5Qe    PKH Address:TnEvLExwzew6LPL13yXmWKnnZxD1c5Lr8Tw module=miner
2022-11-12|00:04:58.212 [INFO ] Start CPU Worker...                 module=miner
2022-11-12|00:04:58.212 [DEBUG] Initialize:data/testnet             module=EVM
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x559a5d8]

goroutine 215 [running]:
github.com/Qitmeer/qng/meerevm/chain.(*MeerChain).MeerPool(...)
	/Users/blocklee/git/node/code/qng/meerevm/chain/meerchain.go:291
github.com/Qitmeer/qng/meerevm/evm.(*VM).GetTxsFromMempool(0x0?)
	/Users/blocklee/git/node/code/qng/meerevm/evm/vm.go:294 +0x18
github.com/Qitmeer/qng/vm.(*Service).GetTxsFromMempool(0x58535e0?)
	/Users/blocklee/git/node/code/qng/vm/service.go:240 +0x4a
github.com/Qitmeer/qng/services/mempool.(*TxPool).MiningDescs(0xc001049ce0)
	/Users/blocklee/git/node/code/qng/services/mempool/mempool.go:1208 +0x1b8
github.com/Qitmeer/qng/services/mining.NewBlockTemplate(0xc02f17a0c0, 0x79e1740, 0x6e25e38?, {0x6a1ee00, 0xc001049ce0}, {0x6a184c0, 0xc001260300?}, 0xc000288d80, {0x6a24150, 0xc000e0dd70}, ...)
	/Users/blocklee/git/node/code/qng/services/mining/newblocktemplate.go:147 +0x369
github.com/Qitmeer/qng/services/miner.(*Miner).updateBlockTemplate(0xc001049e40, 0x2a?)
	/Users/blocklee/git/node/code/qng/services/miner/miner.go:314 +0x1e5
github.com/Qitmeer/qng/services/miner.(*CPUWorker).Start(0xc01d5d41b0)
	/Users/blocklee/git/node/code/qng/services/miner/cpuworker.go:77 +0x85
github.com/Qitmeer/qng/services/miner.(*Miner).handler(0xc001049e40)
	/Users/blocklee/git/node/code/qng/services/miner/miner.go:135 +0xeaa
created by github.com/Qitmeer/qng/services/miner.(*Miner).Start
	/Users/blocklee/git/node/code/qng/services/miner/miner.go:92 +0xc5
(base) blocklee@Mac node % 
```

**Comment by blocklee** [comment]
This problem has been fixed on ing-version-1.0.18
