### ISSUE TITLE
mempool panic

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qng#285]
QNG version 1.0.19+dev-699cfda

Occurred tiwce. Occurred after running for a long time.

```bash
panic: runtime error: index out of range [-1]

goroutine 288 [running]:
github.com/Qitmeer/qng/services/mempool.(*FeeEstimator).RegisterBlock(0xc0003982c0, 0xc0276b5880)
	/Users/blocklee/git/qng/services/mempool/estimatefee.go:275 +0xb48
github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).handleNotifyMsg(0xc008f066c0, 0xc00754a138)
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:223 +0x6c5
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).sendNotification(0xc000000780, 0x1, {0x57173e0?, 0xc00a1a7b00})
	/Users/blocklee/git/qng/core/blockchain/notifications.go:105 +0xea
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc000000780, 0xc0276b5880, 0x4)
	/Users/blocklee/git/qng/core/blockchain/accept.go:180 +0x75f
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).ProcessBlock(0xc000000780, 0xc0276b5880, 0x4)
	/Users/blocklee/git/qng/core/blockchain/process.go:147 +0xa4f
github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).blockHandler(0xc008f066c0)
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:390 +0x7ad
created by github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).Start
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:282 +0xaa
```

```bash
2022-11-16|18:30:34.397 [INFO ] Syncing to state (487757,487505,487505,491570,1) from peer 16Uiu2HAm545p6wc5k83R7mbKbLLH3Ca6dbFZdPspsvbThNytjiiU cur graph state:(487756,487504,487504,490137,1) module=SYNC
DEBUG[11-16|18:30:34.653] Persisted trie from memory database      nodes=10 size=2.82KiB time="87.837µs"  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-16|18:30:34.654] Persisted trie from memory database      nodes=10 size=2.82KiB time="51.675µs"  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-16|18:30:34.654] Persisted trie from memory database      nodes=10 size=2.82KiB time="139.229µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [11-16|18:30:34.654] Imported new chain segment               blocks=1 txs=1 mgas=0.021 elapsed="530.953µs" mgasps=39.552 number=707 hash=3bdccb..e12a25 dirty=0.00B
DEBUG[11-16|18:30:34.655] Inserted new block                       number=707 hash=3bdccb..e12a25 uncles=0 txs=1 gas=21000 elapsed="597.833µs" root=2630f9..51d081
2022-11-16|18:30:34.655 [DEBUG] MeerEVM Block:number=707 hash=0x3bdccb7683cd3df1569253fd621ef4622951dc6441f5f7c2cf24fdf560e12a25 txs=1  => blockHash(0x3b8c1dd67f3d27d0f894c493a22c407ae53b3d12d96d9568cbdb8067f49466c1) txs=1 module=EVMC
DEBUG[11-16|18:30:34.655] Reinjecting stale transactions           count=0
2022-11-16|18:30:34.655 [DEBUG] Update meerpool                     module=EVMC       number=708 txs=0 gas=0 fees=0 elapsed=92.604µs
2022-11-16|18:30:34.655 [DEBUG] Block connected to the main chain   module=blockchain hash=3b8c1dd67f3d27d0f894c493a22c407ae53b3d12d96d9568cbdb8067f49466c1 order=487757
2022-11-16|18:30:34.655 [DEBUG] Meer pool:remove tx df7bd7aa298a677d6e898749efe9b7e9f00809afd62d4cc1988cff925e0f73fe(0x60eb798b1b4ac5b337d86287e735506ad1387d35417c6e7b308f4c4f78f55941) module=EVMC
panic: runtime error: index out of range [-1]

goroutine 157 [running]:
github.com/Qitmeer/qng/services/mempool.(*FeeEstimator).RegisterBlock(0xc000fed080, 0xc02bae1a40)
	/Users/blocklee/git/qng/services/mempool/estimatefee.go:275 +0xb48
github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).handleNotifyMsg(0xc000290d80, 0xc0228af278)
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:223 +0x6c5
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).sendNotification(0xc000000780, 0x1, {0x57173e0?, 0xc0228aeab0})
	/Users/blocklee/git/qng/core/blockchain/notifications.go:105 +0xea
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc000000780, 0xc02bae1a40, 0x4)
	/Users/blocklee/git/qng/core/blockchain/accept.go:180 +0x75f
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).ProcessBlock(0xc000000780, 0xc02bae1a40, 0x4)
	/Users/blocklee/git/qng/core/blockchain/process.go:147 +0xa4f
github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).blockHandler(0xc000290d80)
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:390 +0x7ad
created by github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).Start
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:282 +0xaa
(base) blocklee@Mac node %
```

**Comment by blocklee** [comment]
occurred again

```bash
2022-11-17|11:05:46.329 [DEBUG] End DAG REORGANIZE: Old Len= 1;New Len= 1 module=blockchain
2022-11-17|11:05:46.329 [INFO ] Processed 1 block in the last 32.84s (1 transaction, order 491717, 2022-11-17 11:05:09 +0800 CST) module=blkmanager
2022-11-17|11:05:46.329 [DEBUG] Accepted block                      module=blockchain hash=22d9de0d80cea9d91e217160c91122084a8db33297d3ea33c89ccef1142bb5b2
DEBUG[11-17|11:05:46.332] Persisted trie from memory database      nodes=19  size=4.86KiB  time="72.891µs"  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-17|11:05:46.333] Persisted trie from memory database      nodes=19  size=4.86KiB  time="56.901µs"  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-17|11:05:46.333] Persisted trie from memory database      nodes=19  size=4.86KiB  time="195.509µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [11-17|11:05:46.333] Imported new chain segment               blocks=1 txs=4 mgas=0.084 elapsed="571.596µs" mgasps=146.957 number=712 hash=7493a6..95795a dirty=0.00B
DEBUG[11-17|11:05:46.333] Inserted new block                       number=712 hash=7493a6..95795a uncles=0 txs=4 gas=84000 elapsed="570.242µs" root=cf2c42..6bf3ec
2022-11-17|11:05:46.333 [DEBUG] MeerEVM Block:number=712 hash=0x7493a6b6b8f7976fff765c8b2accd183802a52674238a46e1fe2ae107895795a txs=4  => blockHash(0xc486a423152957ad5966fbd24bd4864285da237fcd34b527d90b30f3fccc802c) txs=4 module=EVMC
DEBUG[11-17|11:05:46.334] Reinjecting stale transactions           count=0
2022-11-17|11:05:46.334 [DEBUG] Update meerpool                     module=EVMC       number=713 txs=0 gas=0 fees=0 elapsed=85.796µs
2022-11-17|11:05:46.334 [DEBUG] Block connected to the main chain   module=blockchain hash=c486a423152957ad5966fbd24bd4864285da237fcd34b527d90b30f3fccc802c order=491718
2022-11-17|11:05:46.334 [DEBUG] Meer pool:remove tx c5e86f8ac1090a256ca7757b493f390a1d67dd737b59ddbb5f2a704c395823ef(0x6c1d4b997904485431e283dc691249156bb9625d519b6dd02be8803053906940) module=EVMC
2022-11-17|11:05:46.334 [DEBUG] Meer pool:remove tx 362ad3cfed362392b4beba3e92be6b00d777305c9d7e013ffc86d92ac1f1fa46(0x9f65aa09dc112124d9d2a0c9e8f14cc3b9d0722892eecb7567cfe22d3763a326) module=EVMC
2022-11-17|11:05:46.334 [DEBUG] Meer pool:remove tx 33cd9999908d486670981b4b322f9554249c5a212fc914bf3eec111983abfeb3(0x616e44163952d7bb28884d496d248c1006ed99d9f6d031743a3d56acbcbf3ad2) module=EVMC
2022-11-17|11:05:46.334 [DEBUG] Meer pool:remove tx b68e9de4c48d305ece234c8d6d2e7a6b66e8b84d9a5ecb663849a523d9aef069(0xd768a3bc8249c05e61a45775d8b88485f7c6eb008bc530d23c0170fb8e7e5579) module=EVMC
panic: runtime error: index out of range [-1]

goroutine 772 [running]:
github.com/Qitmeer/qng/services/mempool.(*FeeEstimator).RegisterBlock(0xc000c12dc0, 0xc038224e70)
	/Users/blocklee/git/qng/services/mempool/estimatefee.go:275 +0xb48
github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).handleNotifyMsg(0xc000b3c900, 0xc0072fdb78)
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:223 +0x6c5
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).sendNotification(0xc000000780, 0x1, {0x57173e0?, 0xc0072fd338})
	/Users/blocklee/git/qng/core/blockchain/notifications.go:105 +0xea
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc000000780, 0xc038224e70, 0x4)
	/Users/blocklee/git/qng/core/blockchain/accept.go:180 +0x75f
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).ProcessBlock(0xc000000780, 0xc038224e70, 0x4)
	/Users/blocklee/git/qng/core/blockchain/process.go:147 +0xa4f
github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).blockHandler(0xc000b3c900)
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:390 +0x7ad
created by github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).Start
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:282 +0xaa
```

**Comment by blocklee** [comment]
```bash
panic: runtime error: index out of range [-1]

goroutine 210 [running]:
github.com/Qitmeer/qng/services/mempool.(*FeeEstimator).RegisterBlock(0xc0000c7b80, 0xc028e2ab60)
	/Users/blocklee/git/qng/services/mempool/estimatefee.go:275 +0xb48
github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).handleNotifyMsg(0xc00026efc0, 0xc01d170c78)
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:245 +0x6a5
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).sendNotification(0xc0005b0a80, 0x1, {0x57113a0?, 0xc01d1707c8})
	/Users/blocklee/git/qng/core/blockchain/notifications.go:105 +0xea
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc0005b0a80, 0xc028e2ab60, 0x4)
	/Users/blocklee/git/qng/core/blockchain/accept.go:180 +0x75f
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).ProcessBlock(0xc0005b0a80, 0xc028e2ab60, 0x4)
	/Users/blocklee/git/qng/core/blockchain/process.go:147 +0xa4f
github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).blockHandler(0xc00026efc0)
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:412 +0x70f
created by github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).Start
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:304 +0xaa
(base) blocklee@Mac node % ./qng -v
QNG version 1.0.18+dev-6f52821
```

```bash
panic: runtime error: index out of range [-1]

goroutine 195 [running]:
github.com/Qitmeer/qng/services/mempool.(*FeeEstimator).RegisterBlock(0xc007464dc0, 0xc00e4418f0)
	/Users/blocklee/git/qng/services/mempool/estimatefee.go:275 +0xb48
github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).handleNotifyMsg(0xc000828120, 0xc00aecaa20)
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:245 +0x6a5
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).sendNotification(0xc000160000, 0x1, {0x57113a0?, 0xc00aeca570})
	/Users/blocklee/git/qng/core/blockchain/notifications.go:105 +0xea
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc000160000, 0xc00e4418f0, 0x4)
	/Users/blocklee/git/qng/core/blockchain/accept.go:180 +0x75f
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).ProcessBlock(0xc000160000, 0xc00e4418f0, 0x4)
	/Users/blocklee/git/qng/core/blockchain/process.go:147 +0xa4f
github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).blockHandler(0xc000828120)
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:412 +0x70f
created by github.com/Qitmeer/qng/services/blkmgr.(*BlockManager).Start
	/Users/blocklee/git/qng/services/blkmgr/blkmgr.go:304 +0xaa
(base) blocklee@Mac node % qng -v
zsh: command not found: qng
(base) blocklee@Mac node % ./qng -v
QNG version 1.0.18+dev-6f52821
```
