### ISSUE TITLE
qng testnet version 1.0.19+dev-0aafb7f run panic when sync from 0

### ISSUE THREAD

**Issue by jamesvan2019** [Qitmeer/qng#327]
### issue 
- qng version *1.0.19+dev-0aafb7f*
- network testnet
- sync from 0
- start script 
```
./build/bin/qng --profile=112  --maxpeers=30 --maxinbound=15 -d debug --printorigin --rpclisten 0.0.0.0:28131 --port=28130 --rpcuser test --rpcpass test --miner  --acceptnonstd -A ./data --modules=log --testnet --modules=test --miningaddr=Tk6uJDaurxqPrg2bZqBa9XSpUcakebZ6EU1u9qqHNDcNW2MyeTtbX --modules=miner --modules=qitmeer --logdir=/root/.qng/logs/  --evmenv="--http --http.port=2234 --ws --ws.port=2235 --http.addr=0.0.0.0" --qit --qitenv="--http --http.port=3234 --ws --ws.port=3235 --http.addr=0.0.0.0"
```

- panic 

```
DEBUG[01-20|19:44:05.101|core/blockchain.go:1738]                                 Inserted new block                       number=24834 hash=271781..a659ed uncles=0 txs=1   gas=21000      elapsed="267.891µs" root=a90f2b..f911f3
2023-01-20|19:44:05.114 [DEBUG|/meerevm/meer/meerchain.go:64]                   MeerEVM Block:number=24834 hash=0x271781d33a2a010ec2083ecb4f007f17c624d329d5d95993fa4047b54ea659ed txs=1  => blockHash(0x3936f4baf1dde33e2b29b0f826dfc49cb6ce75d16f40d5dc2a401cd51b8cb462) txs=1module=EVMC
2023-01-20|19:44:05.115 [DEBUG|/core/blockchain/blockchain.go:746]              End DAG REORGANIZE: Old Len= 2;New Len= 1module=blockchain
DEBUG[01-20|19:44:05.103|core/tx_pool.go:1304]                                    Reinjecting stale transactions           count=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf25fb1]

goroutine 197538 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(...)
        /root/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.10.26-q.3/core/types/block.go:295
github.com/ethereum/go-ethereum/core.(*TxPool).reset(0xc00003c800, 0xc0123d8900, 0xc0123d8fc0)
        /root/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.10.26-q.3/core/tx_pool.go:1260 +0xe91
github.com/ethereum/go-ethereum/core.(*TxPool).runReorg(0xc00003c800, 0xc0132e4f60, 0xc030501040, 0x0, 0xc04110d9e0)
        /root/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.10.26-q.3/core/tx_pool.go:1164 +0x26b
created by github.com/ethereum/go-ethereum/core.(*TxPool).scheduleReorgLoop
        /root/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.10.26-q.3/core/tx_pool.go:1093 +0x1b3
```

**Comment by jamesvan2019** [comment]
`fixed` use latest version
