### ISSUE TITLE
bugs occurred when Import account into QNG node

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qng#340]
qng version QNG version 1.0.19+dev-9b6710b

macOS Ventura 13.2

- panic when running "./qng --testnet -A=./ account new"

```bash
% ./testqng --testnet -A=./ account new
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x101004198]

goroutine 1 [running]:
github.com/Qitmeer/qng/meerevm/cmd.accountCreate(0x103a53780?)
	/Users/blocklee/git/qng/meerevm/cmd/accountcmd.go:194 +0x38
github.com/urfave/cli/v2.(*Command).Run(0x103a53780, 0xc000b70200)
	/Users/blocklee/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/command.go:169 +0x631
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000003d40, 0xc000431f80)
	/Users/blocklee/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/app.go:490 +0xd0a
github.com/urfave/cli/v2.(*Command).startApp(0x103a530c0, 0xc000431f80)
	/Users/blocklee/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/command.go:287 +0x77b
github.com/urfave/cli/v2.(*Command).Run(0x10174d0a0?, 0xc000cd2cb0?)
	/Users/blocklee/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc000502d00, {0x102a66930?, 0xc00013a008}, {0xc00013e000, 0x5, 0x5})
	/Users/blocklee/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/app.go:341 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/blocklee/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/app.go:247
main.qng()
	/Users/blocklee/git/qng/cmd/qng/qng.go:64 +0x410
main.main()
	/Users/blocklee/git/qng/cmd/qng/qng.go:38 +0x35
```

- error occurred when running "./qng --testnet -A=./ account import"

```bash
 % ./testqng --testnet -A=./ account import ./data/testnet/keystore/UTC--2022-11-26T15-19-48.244130000Z--b3511418f51f3851138874dce3c146e9958fa9f1 
Fatal: Failed to load the private key: invalid character '"' at end of key file
```

**Comment by dindinw** [comment]
can't reproduce, please try the latest trunk code  
```
./qng -V
qng version 1.0.19+dev-a5239b1 (Go version go1.20)

./qng --testnet -A . account new
INFO [02-15|14:55:28.014] New local node record                    seq=1,676,444,128,014 id=d98bf148052013cb ip=127.0.0.1 udp=8538 tcp=0
INFO [02-15|14:55:28.015] Maximum peer count                       ETH=0 LES=0 total=0
Your new account is locked with a password. Please give a password. Do not forget this password.
Password: ^C
```
