### ISSUE TITLE
panic: unable to find block 

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qng#361]
- QNG version:QNG version 1.0.20+dev-a621440

- BUG log

Stopped by itself during running：

```bash
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: 2023-04-03|17:30:33.082 [DEBUG] Start DAG REORGANIZE: Block 57dbac0c54667be48ce1784ec4148f73af521a123c9e6c7999df5408d734e9a1 is causing a reorganize. module=CHAIN
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: panic: unable to find block 0d4038916e65b5ddc01e66c1f6f2f91d8cc4661197dd63846d65b3c339912e45 db
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: goroutine 1102437 [running]:
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/core/blockchain.(*BlockChain).reorganizeChain(0xc000d4a700, {0x35d5978, 0xc076f7e820}, 0xc022c23d10, 0xc022c23e00, 0xc02b3710a0, 0x0?)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/core/blockchain/blockchain.go:653 +0xe58
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/core/blockchain.(*BlockChain).connectDagChain(0xc000d4a700, {0x35d5978, 0xc076f7e820}, 0xc078274e00?, 0xc022c23e00, 0xc022c23d10, 0xc102c50e4453a2c9?)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/core/blockchain/process.go:368 +0x6ea
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc000d4a700, 0xc02b3710a0, 0x4)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/core/blockchain/process.go:247 +0x587
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/core/blockchain.(*BlockChain).processBlock(0x6fd2f8?, 0xc02b3710a0, 0x7059aa01?)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/core/blockchain/process.go:56 +0x57
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/core/blockchain.(*BlockChain).ProcessBlock(0x2198fc0?, 0xc0450af690?, 0x300?)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/core/blockchain/process.go:45 +0x90
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/p2p/synch.(*PeerSync).processGetBlockDatas(0xc010efebe0, 0x8?, {0xc0624fa680, 0x8, 0x1?})
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/p2p/synch/getblockdatas.go:238 +0xe9f
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/p2p/synch.(*PeerSync).processSyncDAGBlocks(0xc010efebe0, 0xc034667ea0?)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/p2p/synch/syncdag.go:133 +0x9f0
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/p2p/synch.(*PeerSync).IntellectSyncBlocks(0xc010efebe0, 0x0, 0xc006bf9dc0)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/p2p/synch/peersync.go:471 +0x5a5
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/p2p/synch.(*PeerSync).startSync(0xc010efebe0)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/p2p/synch/peersync.go:327 +0x857
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/p2p/synch.(*PeerSync).updateSyncPeer(0xc010efebe0, 0x0)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/p2p/synch/peersync.go:489 +0x125
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/p2p/synch.(*PeerSync).OnPeerConnected(0xc010efebe0, 0xc0173b1c70?)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/p2p/synch/peersync.go:206 +0x152
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/p2p/synch.(*PeerSync).Connection(0xc010efebe0, 0x35af138?)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/p2p/synch/handshake.go:117 +0x2cb
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: github.com/Qitmeer/qng/p2p/synch.(*PeerSync).processConnected(0xc010efebe0, 0xc038ecf6c0)
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/p2p/synch/handshake.go:88 +0x614
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]: created by github.com/Qitmeer/qng/p2p/synch.(*PeerSync).Connected
Apr 03 17:30:33 VM-0-14-ubuntu start.sh[661078]:         /home/ubuntu/qng/p2p/synch/handshake.go:39 +0x10d
Apr 03 17:30:33 VM-0-14-ubuntu systemd[1]: qitmeer-testnet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 03 17:30:33 VM-0-14-ubuntu systemd[1]: qitmeer-testnet.service: Failed with result 'exit-code'.
```

when restart again:

```bash
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.951 [INFO ] Chain ID:  223 (unknown)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.951 [INFO ] Consensus: Ethash (proof-of-work)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.951 [INFO ]
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.951 [INFO ] Pre-Merge hard forks (block based):
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.951 [INFO ]  - Homestead:                   #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.951 [INFO ]  - DAO Fork:                    #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/dao-fork.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.951 [INFO ]  - Tangerine Whistle (EIP 150): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.951 [INFO ]  - Spurious Dragon/1 (EIP 155): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.951 [INFO ]  - Spurious Dragon/2 (EIP 158): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.951 [INFO ]  - Byzantium:                   #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]  - Constantinople:              #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]  - Petersburg:                  #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]  - Istanbul:                    #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]  - Muir Glacier:                #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/muir-glacier.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]  - Berlin:                      #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]  - London:                      #<nil> (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md)
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ] The Merge is not yet available for this network!
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]  - Hard-fork specification: https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ] Post-Merge hard forks (timestamp based):
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ] ---------------------------------------------------------------------------------------------------------------------------------------------------------
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.952 [INFO ]
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.956 [INFO ] Loaded most recent local block      number=12019 hash=f1b61e..7733b1 td=12019 age=4h59m
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.960 [WARN ] Head state missing, repairing       number=12019 hash=f1b61e..7733b1 snaproot=fbfc56..38aa0a
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.999 [DEBUG] Skipping block with threshold state number=11565 hash=4ce3f3..22310d root=0eda52..a80e9a
Apr 03 22:29:24 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:24.999 [DEBUG] Skipping block with threshold state number=11564 hash=6f5c97..4581b5 root=e639a7..10f461
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.001 [DEBUG] Skipping block with threshold state number=11555 hash=803294..644c8a root=af22d8..386613
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.001 [DEBUG] Skipping block with threshold state number=11554 hash=676403..8a1d6a root=702e8f..9e50fb
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.016 [DEBUG] Skipping block with threshold state number=11428 hash=e68b68..a6ed08 root=15b2ee..e30f6b
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.281 [DEBUG] Rewound to block with state         number=9240  hash=6210e2..f2c4ed
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.282 [INFO ] Loaded most recent local header     number=12019 hash=f1b61e..7733b1 td=12019 age=4h59m1s
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.282 [INFO ] Loaded most recent local block      number=9240  hash=6210e2..f2c4ed td=9240  age=17h19s
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.282 [INFO ] Loaded most recent local snap block number=12019 hash=f1b61e..7733b1 td=12019 age=4h59m1s
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.282 [WARN ] Enabling snapshot recovery          chainhead=9240 diskbase=9241
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.294 [WARN ] Snapshot is not continuous with chain snaproot=0eda52..a80e9a chainroot=76acb8..5adca4
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.295 [DEBUG] Reinjecting stale transactions      count=0
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.295 [WARN ] Switch sync mode from snap sync to full sync
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.296 [DEBUG] Temporarily not supported: SetExtra module=MEER
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.296 [INFO ] Gasprice oracle is ignoring threshold set threshold=2
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.297 [WARN ] Unclean shutdown detected           booted=2023-04-01T17:49:54+0800 age=2d4h39m
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.297 [WARN ] Unclean shutdown detected           booted=2023-04-03T17:28:56+0800 age=5h29s
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.298 [INFO ] Meer pool init...                   module=MEER
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.298 [ERROR] Illegal withdrawal at block:a1e934d70854df99796c9e3c121a52af738f14c44e78e18ce47b66540cacdb57, you can cleanup your block data base by '--cleanup'. module=SHUT
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.298 [INFO ] Gracefully shutting down the database...
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.306 [INFO ] Shutdown complete
Apr 03 22:29:25 VM-0-14-ubuntu start.sh[766273]: 2023-04-03|22:29:25.306 [ERROR] Illegal withdrawal at block:a1e934d70854df99796c9e3c121a52af738f14c44e78e18ce47b66540cacdb57, you can cleanup your block data base by '--cleanup'.
Apr 03 22:29:25 VM-0-14-ubuntu systemd[1]: qitmeer-testnet.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 22:29:25 VM-0-14-ubuntu systemd[1]: qitmeer-testnet.service: Failed with result 'exit-code'.
```

**Comment by dindinw** [comment]
The local data is corrupt. 
1.  please update to the latest code since you are using  the `1.20-dev` version. 
2. do the `--cleanup` and re-sync the data again

**Comment by blocklee** [comment]
ok 👌
