### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qng#369]
- A pannic occurs on the main network node and data is damaged.

```bash
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.361 [DEBUG] MeerEVM Block:number=481808 hash=0x02bb73b5aae5f157fedc4438cc2bb5f8a64c5623a4b01ef6a3d2c82db2>
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.361 [DEBUG] Block connected to the main chain   module=CHAIN     hash=df35c6b6602dc8ed90206aedae6ee2d39e1>
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.362 [DEBUG] Meer pool:remove tx a424f43d7c28daab9b4ead6340e58d28a16cb3af55b2f4edfc63bdd73e844b0f(0xbe603a>
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.362 [DEBUG] Update meerpool                     module=MEER      number=481809 txs=0   gas=0        fees=>
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.362 [DEBUG] Accepted block                      module=CHAIN     hash=df35c6b6602dc8ed90206aedae6ee2d39e1>
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.362 [DEBUG] Start DAG REORGANIZE: Block b7e514360b01a41bcafc66e0a792ff9b8a6dc060a7b9acac8544382a5738dfe2 >
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.363 [WARN ] Rewinding blockchain                target=481807
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.363 [DEBUG] Rewound to block with state         number=481807 hash=59850e..a6f6bb
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.363 [INFO ] Loaded most recent local header     number=481807 hash=59850e..a6f6bb                        >
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.363 [INFO ] Loaded most recent local full block number=481807 hash=59850e..a6f6bb                        >
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.363 [INFO ] Loaded most recent local fast block number=481807 hash=59850e..a6f6bb                        >
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.363 [DEBUG] Reorganize:0x02bb73b5aae5f157fedc4438cc2bb5f8a64c5623a4b01ef6a3d2c82db22d22da(481808) => 0x59>
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: 2023-04-09|06:21:28.363 [DEBUG] Reinjecting stale transactions      count=0
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xed97aa]
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: goroutine 240062132 [running]:
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(...)
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]:         /Users/alex/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.10.26-q.3/core/types/block.go:295
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: github.com/ethereum/go-ethereum/core.(*TxPool).reset(0xc006db7800, 0xc02fe506c0, 0xc02fe518c0)
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]:         /Users/alex/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.10.26-q.3/core/tx_pool.go:1260 +0xdea
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: github.com/ethereum/go-ethereum/core.(*TxPool).runReorg(0xc006db7800, 0xc06abe0000, 0xc060d5e2d0, 0x0, 0xc075b5df50)
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]:         /Users/alex/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.10.26-q.3/core/tx_pool.go:1164 +0x26b
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]: created by github.com/ethereum/go-ethereum/core.(*TxPool).scheduleReorgLoop
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ start.sh[1849335]:         /Users/alex/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.10.26-q.3/core/tx_pool.go:1093 +0x1b0
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ systemd[1]: meer-test.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ systemd[1]: meer-test.service: Failed with result 'exit-code'.
Apr 09 06:21:28 iZ2vcbzjv5017f7djkb00wZ systemd[1]: meer-test.service: Consumed 1d 22h 2min 29.275s CPU time.
```

A reboot shows data corruption.

```bash
2023-04-10|10:37:45.973 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=receipts items=7      limit=6
2023-04-10|10:37:45.973 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=diffs    items=7      limit=6
2023-04-10|10:37:45.973 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=headers  items=7      limit=6
2023-04-10|10:37:45.973 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=headers  items=6      limit=5
2023-04-10|10:37:45.973 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=hashes   items=6      limit=5
2023-04-10|10:37:45.973 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=bodies   items=6      limit=5
2023-04-10|10:37:45.973 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=receipts items=6      limit=5
2023-04-10|10:37:45.973 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=diffs    items=6      limit=5
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=hashes   items=5      limit=4
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=bodies   items=5      limit=4
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=receipts items=5      limit=4
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=diffs    items=5      limit=4
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=headers  items=5      limit=4
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=headers  items=4      limit=3
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=hashes   items=4      limit=3
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=bodies   items=4      limit=3
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=receipts items=4      limit=3
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=diffs    items=4      limit=3
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=headers  items=3      limit=2
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=hashes   items=3      limit=2
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=bodies   items=3      limit=2
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=receipts items=3      limit=2
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=diffs    items=3      limit=2
2023-04-10|10:37:45.974 [DEBUG] Rewound to block with state         number=0      hash=6cff87..0208fc
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=bodies   items=2      limit=1
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=receipts items=2      limit=1
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=diffs    items=2      limit=1
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=headers  items=2      limit=1
2023-04-10|10:37:45.974 [DEBUG] Truncating freezer table            database=/root/qitmeer/node/data/mainnet/meereth/chaindata/ancient table=hashes   items=2      limit=1
2023-04-10|10:37:49.214 [DEBUG] Current full block not old enough   number=0      hash=6cff87..0208fc delay=90000
2023-04-10|10:37:49.961 [INFO ] Loaded most recent local header     number=0      hash=6cff87..0208fc td=0      age=1y6mo2w
2023-04-10|10:37:49.961 [INFO ] Loaded most recent local full block number=0      hash=6cff87..0208fc td=0      age=1y6mo2w
2023-04-10|10:37:49.961 [INFO ] Loaded most recent local fast block number=0      hash=6cff87..0208fc td=0      age=1y6mo2w
2023-04-10|10:37:49.962 [WARN ] Enabling snapshot recovery          chainhead=0 diskbase=481642
2023-04-10|10:37:49.975 [WARN ] Loaded snapshot journal             diskroot=25ec6d..c57656 diffs=unmatched
2023-04-10|10:37:49.975 [WARN ] Snapshot is not continuous with chain snaproot=25ec6d..c57656 chainroot=139989..a86518
2023-04-10|10:37:49.989 [DEBUG] Reinjecting stale transactions      count=0
2023-04-10|10:37:49.994 [DEBUG] Temporarily not supported: SetExtra module=MEER
2023-04-10|10:37:49.998 [INFO ] Gasprice oracle is ignoring threshold set threshold=2
2023-04-10|10:37:49.999 [WARN ] Unclean shutdown detected           booted=2023-04-09T06:18:20+0800 age=1d4h19m
2023-04-10|10:37:50.017 [INFO ] Meer pool init...                   module=MEER
2023-04-10|10:37:50.018 [ERROR] Illegal withdrawal at block:e2df38572a384485acacb9a760c06d8a9bff92a7e066fcca1ba4010b3614e5b7, you can cleanup your block data base by '--cleanup'. module=SHUT
2023-04-10|10:37:50.020 [INFO ] Gracefully shutting down the database... 
2023-04-10|10:37:50.028 [INFO ] Shutdown complete 
2023-04-10|10:37:50.028 [ERROR] Illegal withdrawal at block:e2df38572a384485acacb9a760c06d8a9bff92a7e066fcca1ba4010b3614e5b7, you can cleanup your block data base by '--cleanup'. 
```

- env

  - qng version: QNG version 1.0.19+release-083abdb

  - Linux Ubuntu 22.04.1 LTS
  
    <img width="606" alt="image" src="https://user-images.githubusercontent.com/32875657/230816916-af17ae27-1a48-4730-9b34-6ab56b4533be.png">

**Comment by blocklee** [comment]
This is a purely synchronous node, without even any rpc calls.

**Comment by dindinw** [comment]
close the v1.0.19 issue. It should has been fixed in the latest release
