### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qng#578]
The node crashed for an unknown reason, and upon restarting, it reported a panic error.

-  QNG Version=1.0.24+release-0c4ed09 
- 

- restart log

```bash
2023-11-28|06:50:49.251 [INFO ] System info                         QNG Version=1.0.24+release-0c4ed09 Go version=go1.19.2
2023-11-28|06:50:49.251 [INFO ] System info                         Home dir=/home/ubuntu/.qng
2023-11-28|06:50:49.251 [INFO ] Loading block database              dbPath=data/mainnet/blocks_ffldb
2023-11-28|06:50:49.277 [INFO ] Block database loaded 
2023-11-28|06:50:49.283 [INFO ] transaction index is enabled        module=INDEX
2023-11-28|06:50:49.284 [INFO ] anticone size:4                     module=DAG
2023-11-28|06:50:49.285 [INFO ] System info                         module=EVM   ETH VM Version=meervm-v0.0.2 Go version=go1.19.2
2023-11-28|06:50:49.331 [INFO ] New local node record               seq=1701154249329 id=17a99f14fd06fb43 ip=127.0.0.1 udp=8538 tcp=0
2023-11-28|06:50:49.337 [INFO ] Prepare meereth on NetWork(813)... 
2023-11-28|06:50:49.338 [INFO ] Maximum peer count                  ETH=0 LES=0 total=0
2023-11-28|06:50:49.339 [INFO ] Smartcard socket not found, disabling err="stat /run/pcscd/pcscd.comm: no such file or directory"
2023-11-28|06:50:49.340 [WARN ] Sanitizing cache to Go's GC limits  provided=4096 updated=2551
2023-11-28|06:50:49.341 [INFO ] Set global gas cap                  cap=50000000
2023-11-28|06:50:49.342 [INFO ] Allocated trie memory caches        clean=382.00MiB dirty=637.00MiB
2023-11-28|06:50:49.343 [INFO ] Using leveldb as the backing database 
2023-11-28|06:50:49.343 [INFO ] Allocated cache and file handles    database=/home/ubuntu/qng/data/mainnet/meereth/chaindata cache=1.24GiB handles=524288
2023-11-28|06:50:49.374 [INFO ] Using LevelDB as the backing database 
2023-11-28|06:50:49.375 [INFO ] Opened ancient database             database=/home/ubuntu/qng/data/mainnet/meereth/chaindata/ancient/chain readonly=false
2023-11-28|06:50:49.388 [INFO ] Disk storage enabled for MeerEngine caches dir=/home/ubuntu/qng/data/mainnet/meereth/ethash count=3
2023-11-28|06:50:49.388 [INFO ] Disk storage enabled for MeerEngine DAGs dir=/home/ubuntu/qng/data/mainnet/meereth/ethash/dataset count=2
2023-11-28|06:50:49.389 [INFO ] Initialising Ethereum protocol      network=813 dbversion=8
2023-11-28|06:50:49.936 [INFO ]  
2023-11-28|06:50:49.936 [INFO ] --------------------------------------------------------------------------------------------------------------------------------------------------------- 
2023-11-28|06:50:49.936 [INFO ] Chain ID:  813 (qng) 
2023-11-28|06:50:49.936 [INFO ] Consensus: MeerDAG (proof-of-work) 
2023-11-28|06:50:49.936 [INFO ]  
2023-11-28|06:50:49.937 [INFO ] Pre-Merge hard forks (block based): 
2023-11-28|06:50:49.937 [INFO ]  - Homestead:                   #0        (EIP-606 Requires:EIP-2, EIP-7, EIP-8) 
2023-11-28|06:50:49.937 [INFO ]  - DAO Fork:                    #0        (EIP-779 Requires:EIP-606) 
2023-11-28|06:50:49.937 [INFO ]  - Tangerine Whistle (EIP 150): #0        (EIP-608 Requires:EIP-150, EIP-779) 
2023-11-28|06:50:49.937 [INFO ]  - Spurious Dragon/1 (EIP 155): #0        (EIP-607 Requires:EIP-155, EIP-160, EIP-161, EIP-170, EIP-608) 
2023-11-28|06:50:49.937 [INFO ]  - Spurious Dragon/2 (EIP 158): #0        (EIP-607 Requires:EIP-155, EIP-160, EIP-161, EIP-170, EIP-608) 
2023-11-28|06:50:49.937 [INFO ]  - Byzantium:                   #0        (EIP-609 Requires:EIP-100, EIP-140, EIP-196, EIP-197, EIP-198, EIP-211, EIP-214, EIP-607, EIP-649, EIP-658) 
2023-11-28|06:50:49.937 [INFO ]  - Constantinople:              #0        (EIP-1013 Requires:EIP-145, EIP-609, EIP-1014, EIP-1052, EIP-1234, EIP-1283) 
2023-11-28|06:50:49.937 [INFO ]  - Petersburg:                  #0        (EIP-1716 Requires:EIP-1013, EIP-1283) 
2023-11-28|06:50:49.937 [INFO ]  - Istanbul:                    #0        (EIP-1679 Requires:EIP-152, EIP-1108, EIP-1344, EIP-1716, EIP-1884, EIP-2028, EIP-2200) 
2023-11-28|06:50:49.937 [INFO ]  - Muir Glacier:                #0        (EIP-2387 Requires:EIP-1679, EIP-2384) 
2023-11-28|06:50:49.937 [INFO ]  - Berlin:                      #0        (EIP-2565 EIP-2929 EIP-2718 EIP-2930 Requires:EIP-198) 
2023-11-28|06:50:49.937 [INFO ]  - London:                      #<nil> (EIP-1559 EIP-3198 EIP-3529 EIP-3541 EIP-3554 Requires:EIP-2718, EIP-2930, EIP-2200, EIP-2929, EIP-2930) 
2023-11-28|06:50:49.937 [INFO ]  
2023-11-28|06:50:49.937 [INFO ] The Merge is not yet available for this network! 
2023-11-28|06:50:49.937 [INFO ]  - Hard-fork specification: EIP-3675 EIP-4399 Requires:EIP-2124 
2023-11-28|06:50:49.937 [INFO ]  
2023-11-28|06:50:49.937 [INFO ] Post-Merge hard forks (timestamp based): 
2023-11-28|06:50:49.937 [INFO ]  
2023-11-28|06:50:49.937 [INFO ] --------------------------------------------------------------------------------------------------------------------------------------------------------- 
2023-11-28|06:50:49.937 [INFO ]  
2023-11-28|06:50:49.937 [INFO ] Initialized database from freezer   blocks=1 elapsed=50.069µs
2023-11-28|06:50:49.938 [INFO ] Loaded most recent local block      number=0 hash=6cff87..0208fc td=0 age=2y2mo1w
2023-11-28|06:50:49.939 [WARN ] Enabling snapshot recovery          chainhead=0 diskbase=1063046
2023-11-28|06:50:49.939 [WARN ] Loaded snapshot journal             diskroot=8a455d..423a6c diffs=unmatched
2023-11-28|06:50:49.939 [WARN ] Snapshot is not continuous with chain snaproot=8a455d..423a6c chainroot=139989..a86518
2023-11-28|06:50:49.939 [INFO ] Loaded local transaction journal    transactions=0 dropped=0
2023-11-28|06:50:49.940 [INFO ] Regenerated local transaction journal transactions=0 accounts=0
2023-11-28|06:50:49.940 [INFO ] Gasprice oracle is ignoring threshold set threshold=2
2023-11-28|06:50:49.940 [WARN ] Unclean shutdown detected           booted=2023-11-27T13:42:24+0000 age=17h8m25s
2023-11-28|06:50:49.940 [WARN ] Unclean shutdown detected           booted=2023-11-28T06:04:32+0000 age=46m17s
2023-11-28|06:50:49.940 [INFO ] Meer pool init...                   module=MEER
2023-11-28|06:50:49.941 [INFO ] Loading dag ...                     module=CHAIN
2023-11-28|06:50:50.189 [INFO ] Dag loaded:loadTime=248.310648ms    module=CHAIN
2023-11-28|06:50:50.199 [INFO ] DAG Type:phantom                    module=CHAIN
2023-11-28|06:50:50.199 [INFO ] Blockchain database version         module=CHAIN chain=13 compression=1 index=1
2023-11-28|06:50:50.199 [INFO ] Chain state:totaltx=9533127 tipsNum=1 mainOrder=2525348 total=2525581 module=CHAIN
2023-11-28|06:50:50.199 [INFO ] hash=4a47aa0ee54899645fd4136581990ceb157c6bbd56bf465f2bdf34a8e32cf1e2,order=2525348,height=2261609 module=CHAIN
2023-11-28|06:50:50.216 [INFO ] Start Peers from:data/mainnet/peerstore module=P2P
2023-11-28|06:50:50.235 [INFO ] ZMQ:Not Supported                   module=zmq
2023-11-28|06:50:50.236 [INFO ] Starting Node                       module=node
2023-11-28|06:50:50.236 [INFO ] Start NotifyMgr... 
2023-11-28|06:50:50.236 [INFO ] Starting Virtual Machines Service   module=vm
2023-11-28|06:50:50.236 [INFO ] Starting peer-to-peer node          instance=meereth/v1.11.5-stable/linux-amd64/go1.19.2
2023-11-28|06:50:50.236 [WARN ] P2P server will be useless, neither dialing nor listening 
2023-11-28|06:50:50.250 [INFO ] New local node record               seq=1682946619522 id=2caabdf7267e85aa ip=127.0.0.1 udp=0    tcp=0
2023-11-28|06:50:50.250 [INFO ] Started P2P networking              self=enode://7f07eaa16a588dbeac378021aadc2adf8a820d6617f0f61130c44503de3b2291abb511d97974c8612e416d7df1d5c6b0c85e0730c6c3590e463279d3e22fe2ec@127.0.0.1:0
2023-11-28|06:50:50.251 [INFO ] HTTP server started                 endpoint=[::]:18545 auth=false prefix= cors=* vhosts=*
2023-11-28|06:50:50.251 [INFO ] WebSocket enabled                   url=ws://[::]:18546
2023-11-28|06:50:50.251 [INFO ] AccountManager enable account mode  module=ACCT
2023-11-28|06:50:50.263 [INFO ] Load account manager info:version=2 dagid=2525581 addrtotal=2/2 module=ACCT
2023-11-28|06:50:50.275 [INFO ] Start MeerDAG:phantom               module=DAG
2023-11-28|06:50:50.275 [INFO ] Start to find cur block state       module=MEER  state.order=2525348 evm.Number=1066159 cur.number=0
2023-11-28|06:50:50.275 [INFO ] RPC server listening on addr:0.0.0.0:18131 module=RPC
2023-11-28|06:51:47.271 [INFO ] Find cur block state                module=MEER  state.order=1056675 evm.Number=0
2023-11-28|06:51:47.271 [INFO ] Try to restore block state for EVM  module=MEER  evm.hash=0xa4cfd95885c9fa8b0caf99d40ef4f86ba2d26cd00cee4eaafaaa564c2e196f2b evm.number=1 state.order=1056676
2023-11-28|06:51:47.271 [INFO ] Stopping Server                     module=node
2023-11-28|06:51:47.271 [INFO ] P2P Service Stop                    module=P2P
2023-11-28|06:51:47.271 [INFO ] Rebroadcast shutting down           module=P2P
2023-11-28|06:51:47.271 [INFO ] P2P PeerSync Stoping...             module=SYNC
2023-11-28|06:51:47.271 [INFO ] P2P PeerSync Stoped                 module=SYNC
2023-11-28|06:51:47.271 [INFO ] Stopping tx manager                 module=txmanager
2023-11-28|06:51:47.271 [INFO ] Stop MeerDAG:phantom                module=DAG
2023-11-28|06:51:47.272 [INFO ] RPC listener done for 0.0.0.0:18131 module=RPC
2023-11-28|06:51:47.272 [INFO ] Close RpcServer Event Subscribe     module=RPC
2023-11-28|06:51:47.276 [INFO ] Stopping Virtual Machines Service   module=vm
2023-11-28|06:51:47.276 [INFO ] HTTP server stopped                 endpoint=[::]:18545
2023-11-28|06:51:47.276 [INFO ] HTTP server stopped                 endpoint=[::]:18546
2023-11-28|06:51:47.277 [INFO ] Ethereum protocol stopped 
2023-11-28|06:51:47.277 [INFO ] Transaction pool stopped 
2023-11-28|06:51:47.277 [ERROR] Failed to journal state snapshot    err="snapshot [0x139989af769a96d259e1eacd3ee594c81b11b39a120576b4132f72eb1ea86518] missing"
2023-11-28|06:51:47.277 [INFO ] Writing clean trie cache to disk    path=/home/ubuntu/qng/data/mainnet/meereth/triecache threads=4
2023-11-28|06:51:47.967 [INFO ] Persisted the clean trie cache      path=/home/ubuntu/qng/data/mainnet/meereth/triecache elapsed=690.641ms
2023-11-28|06:51:47.971 [INFO ] Blockchain stopped 
2023-11-28|06:51:48.008 [INFO ] Meer pool stopping                  module=MEER
2023-11-28|06:51:48.024 [INFO ] Meer pool stopped                   module=MEER
2023-11-28|06:51:48.024 [INFO ] try stop NotifyMgr 
2023-11-28|06:51:48.032 [INFO ] Stop NotifyMgr... 
2023-11-28|06:51:48.032 [INFO ] Gracefully shutting down the database... 
2023-11-28|06:51:48.309 [INFO ] Shutdown complete 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe390eb]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Number(...)
        /home/ubuntu/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.11.5-q.4/core/types/block.go:324
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc000703c00?, {0xc0752ab5e0?, 0x1?, 0x1?}, 0x1?, 0x1?)
        /home/ubuntu/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.11.5-q.4/core/blockchain.go:1544 +0xab
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc000703c00, {0xc0752ab5e0?, 0x1, 0x1})
        /home/ubuntu/go/pkg/mod/github.com/!qitmeer/go-ethereum@v1.11.5-q.4/core/blockchain.go:1526 +0xb51
github.com/Qitmeer/qng/meerevm/meer.(*MeerChain).prepareEnvironment(0xc0008e2a60, {0x363ae20, 0xc0009ec6e0})
        /home/ubuntu/qng-src/qng/meerevm/meer/meerchain.go:327 +0x10aa
github.com/Qitmeer/qng/meerevm/meer.(*MeerChain).PrepareEnvironment(...)
        /home/ubuntu/qng-src/qng/meerevm/meer/meerchain.go:344
github.com/Qitmeer/qng/meerevm/evm.(*VM).PrepareEnvironment(0x17c7d80?, {0x363ae20?, 0xc0009ec6e0?})
        /home/ubuntu/qng-src/qng/meerevm/evm/vm.go:369 +0x27
github.com/Qitmeer/qng/vm.(*Service).PrepareEnvironment(0xc000af28c0?, {0x363ae20, 0xc0009ec6e0})
        /home/ubuntu/qng-src/qng/vm/service.go:399 +0x5a
github.com/Qitmeer/qng/core/blockchain.(*BlockChain).Start(0xc000d48b40)
        /home/ubuntu/qng-src/qng/core/blockchain/blockchain.go:421 +0x149
github.com/Qitmeer/qng/node/service.(*ServiceRegistry).StartAll(0xc0008e2300)
        /home/ubuntu/qng-src/qng/node/service/serviceregistry.go:48 +0x1df
github.com/Qitmeer/qng/node/service.(*Service).Start(0xc000fe2230)
        /home/ubuntu/qng-src/qng/node/service/service.go:29 +0x105
github.com/Qitmeer/qng/node/service.(*ServiceRegistry).StartAll(0xc0008e2280)
        /home/ubuntu/qng-src/qng/node/service/serviceregistry.go:48 +0x1df
github.com/Qitmeer/qng/node/service.(*Service).Start(0xc000b785a0)
        /home/ubuntu/qng-src/qng/node/service/service.go:29 +0x105
github.com/Qitmeer/qng/node.(*Node).Start(0xc000b785a0)
        /home/ubuntu/qng-src/qng/node/node.go:62 +0xc5
main.qitmeerd(0xc000e10400?)
        /home/ubuntu/qng-src/qng/cmd/qng/qng.go:174 +0x925
github.com/urfave/cli/v2.(*App).RunContext(0xc0009dce00, {0x361ce70?, 0xc000056088}, {0xc000052060, 0x2, 0x2})
        /home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/app.go:395 +0xfe8
github.com/urfave/cli/v2.(*App).Run(...)
        /home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/app.go:252
main.qng()
        /home/ubuntu/qng-src/qng/cmd/qng/qng.go:64 +0x307
main.main()
        /home/ubuntu/qng-src/qng/cmd/qng/qng.go:38 +0x35

```

**Comment by dindinw** [comment]
@blocklee please try the latest 1.0 version at (https://github.com/Qitmeer/qng/tree/dev/1.0)
or the 1.2 dev version at (https://github.com/Qitmeer/qng/tree/dev/1.2)
